# Generated by Django 3.2.2 on 2021-06-03 09:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='voted_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
